version: "3.8"

services:
  mysql-db:
    image: mysql:latest
    restart: always
    container_name: mysql-wikirap
    ports:
      - "3306:3306" #HOST_PORT(3306)
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: fsg2021
      MYSQL_DATABASE: wikirap
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql-db
    depends_on:
      - mysql-db

  back:
    build: ./back
    container_name: backend_wikirap
    ports:
      - "8082:8082" #HOST_PORT(8082)
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/wikirap
      - spring.datasource.username=root
      - spring.datasource.password=fsg2021
    depends_on:
      - mysql-db

volumes:
  mysql_data: