version: "3.8"

services:
  mysql-db:
    image: mysql:latest
    restart: always
    container_name: mysql-wikirap
    ports:
      - "5412:3306" #HOST_PORT(5412)
    volumes:
      - ./back/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: fsg2021
      MYSQL_DATABASE: wikirap

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    restart: always
    ports:
      - "8091:8081" #HOST_PORT(8091)

  back:
    build: ./back
    container_name: backend_wikirap
    ports:
      - "8082:8080" #HOST_PORT(8082)
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/wikirap
      - spring.datasource.username=root
      - spring.datasource.password=fsg2021
    depends_on:
      - mysql-db
